app/phantom/views.py
#-*- coding: utf-* -*-
import json
import time

from app import csrf
from app import db
from app import lib
from app import login_manager, login_required, logout_required, login_user, logout_user, current_user
from flask import Blueprint, Response, request, render_template, flash, g, session, redirect, url_for, abort, jsonify
from flask.ext.paginate import Pagination

from .forms import LoginForm, RegisterForm, AddStorageForm, AddTaskForm
from .models import User, Storage, Task, TaskResult

module = Blueprint('phantom', __name__)

@module.route('/', methods=['GET'])
def index():
    if User.query.count() == 0:
        form = RegisterForm()
        return render_template('index_first.html', form=form)
    elif not current_user.is_authenticated():
        form = LoginForm()
        return render_template('user/login.html', form=form, login_url=url_for('.login'))

    return render_template('index.html')

@module.route('/users/register', methods=['POST'])
@logout_required
def register():
    if User.query.count() > 0:
        abort(403)

    form = RegisterForm()
    if request.method == 'POST' and form.validate():
        user = User(form.data['email'], form.data['password'], True)
        db.session.add(user)
        db.session.commit()
        if user:
            flash('created your account. please sign in.')
            return redirect('/')

    return render_template('index_first.html', form=form)

@module.route('/users/login', methods=['POST'])
@logout_required
def login():
    form = LoginForm()
    if form.validate():
        user = User.query.filter_by(email=form.data['email']).first()
        login_user(user)
        return redirect(request.args.get('next') or '/')

    return render_template('user/login.html', form=form, login_url=url_for('.login'))

@module.route('/user/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect('/')

@module.route('/storages', methods=['GET', 'POST', 'PUT', 'DELETE'])
@login_required
def storages():
    if request.method == 'GET':
        storages = Storage.query.all()
        if request.is_xhr:
            data = [{ 'value': stor.id, 'text': stor.name } for stor in storages]
            return json.dumps(data)
        storages = Storage.query.all()
        add_form = AddStorageForm()
        return render_template('storage/list.html', storages=storages, add_form=add_form)
    elif request.method == 'POST':
        add_form = AddStorageForm()
        if add_form.validate():
            storage = Storage(add_form.data['name'], add_form.data['path'])
            db.session.add(storage)
            db.session.commit()
            return jsonify(success=True)
        else:
            errors = []
            for field, msg in add_form.errors.iteritems():
                for m in msg:
                    errDict = {
                        'field': field,
                        'error': m,
                    }
                    errors.append(errDict)
            return jsonify(success=False, errors=errors)
    elif request.method == 'PUT':
        pk = request.form.get('pk')
        value = request.form.get('value')
        storage = Storage.query.get(pk)

        if not value:
            return jsonify(success=False, msg='Required')
        if not storage:
            return jsonify(success=False, msg='Storage not found')
        else:
            storage.name = value
            db.session.commit()
            return jsonify(success=True)
    elif request.method == 'DELETE':
        pk = request.form.get('pk')
        value = request.form.get('value')
        storage = Storage.query.get(pk)

        if not current_user.check_password(value):
            return jsonify(success=False, msg='Wrong password')
        if not storage:
            return jsonify(success=False, msg='Storage not found')
        else:
            db.session.delete(storage)
            db.session.commit()
            return jsonify(success=True)

@module.route('/tasks', methods=['GET', 'POST', 'PUT', 'DELETE'])
@login_required
def tasks():
    if request.method == 'GET':
        storage_id = request.args.get('storage')
        if storage_id:
            storage = Storage.query.get(storage_id)

        if storage_id and storage:
            tasks = Task.query.filter_by(storage=storage)
        else:
            tasks = Task.query.all()
        add_form = AddTaskForm()

        return render_template('task/list.html', tasks=tasks, add_form=add_form)
    elif request.method == 'POST':
        add_form = AddTaskForm()
        if add_form.validate():
            data = add_form.data
            task = Task(data['storage'], data['name'], data['backup_path'],
                data['backup_time'], data['max_stores'], data['filename_rule'])
            db.session.add(task)
            db.session.commit()
            return jsonify(success=True)
        else:
            errors = []
            for field, msg in add_form.errors.iteritems():
                for m in msg:
                    errDict = {
                        'field': field,
                        'error': m,
                    }
                    errors.append(errDict)
            return jsonify(success=False, errors=errors)
    elif request.method == 'PUT':
        pk = request.form.get('pk')
        name = request.form.get('name')
        value = request.form.get('value')
        task = Task.query.get(pk)

        if not value:
            return jsonify(success=False, msg='Required')
        if not task:
            return jsonify(success=False, msg='Task not found')
        else:
            if name == 'name':
                task.name = value
                db.session.commit()
                return jsonify(success=True)
            elif name == 'storage':
                storage = Storage.query.get(value)
                if storage:
                    task.storage = storage
                    db.session.commit()
                    return jsonify(success=True)
                else:
                    return jsonify(success=False, msg='Storage not found')
            elif name == 'time':
                if not value.isdigit():
                    return jsonify(success=False, msg='Value is not number')
                else:
                    task.backup_time = int(value)
                    db.session.commit()
                    return jsonify(sucecss=True)
    elif request.method == 'DELETE':
        pk = request.form.get('pk')
        value = request.form.get('value')
        task = Task.query.get(pk)

        if not current_user.check_password(value):
            return jsonify(success=False, msg='Wrong password')
        if not task:
            return jsonify(success=False, msg='Task not found')
        else:
            db.session.delete(task)
            db.session.commit()
            return jsonify(success=True)

@module.route('/tasks/result', methods=['GET', 'DELETE'])
@login_required
def task_results():
    if request.method == 'GET':
        results = None
        task = None
        task_id = request.args.get('task')
        if task_id:
            task = task.query.get(task_id)

        return render_template('task/result.html', results=results)

app/templates/base.html
{% if not current_user.is_authenticated() %}
{% set navigation_bar = [
    (url_for('phantom.index'), 'index', 'Main'),
] -%}
{% else %}
{% set navigation_bar = [
    (url_for('phantom.index'), 'index', 'Dashboard'),
    (url_for('phantom.storages'), 'storages', 'Storages'),
    (url_for('phantom.tasks'), 'tasks', 'Tasks'),
    (url_for('phantom.task_results'), 'results', 'Results'),
    (url_for('phantom.index'), 'explore', 'Explore'),
] -%}
{% endif %}
{% set active_page = active_page|default('index') -%}
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}Phantom{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.editable.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/disk.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fix.css') }}">
    <!--[if lt IE 9]>
        <script src="{{ url_for('static', filename='js/html5shiv.js') }}"></script>
        <script src="{{ url_for('static', filename='js/respond.min.js') }}"></script>
    <![endif]-->
</head>
<body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('phantom.index') }}">Phantom</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    {% for href, id, caption in navigation_bar %}
                    <li{% if id == active_page %} class="active"{% endif %}>
                        <a href="{{ href|e }}">{{ caption|e }}</a>
                    </li>
                    {% endfor %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated() %}
                    <li>
                        <a href="{{ url_for('phantom.logout') }}">Sign out</a>
                    </li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flashes">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

        {% block body %}{% endblock %}
    </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.pjax.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.editable.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/application.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='js/site.min.js') }}"></script> -->
    <script>
    var csrftoken = $('meta[name=csrf-token]').attr('content');
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type)) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken)
            }
        }
    });
    </script>
    {% block script %}{% endblock %}
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% set active_page = "index" %}
{% block body %}
{% endblock %}

app/templates/index_first.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no"> 
    <title>Welcome to Phantom!</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/disk.css') }}">
    <!--[if lt IE 9]>
        <script src="{{ url_for('static', filename='js/html5shiv.js') }}"></script>
        <script src="{{ url_for('static', filename='js/respond.min.js') }}"></script>
    <![endif]-->
</head>
<body>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('phantom.index') }}">Phantom</a>
            </div>
            <div class="navbar-collapse collapse">
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class="flashes">
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Sign Up</h3>
            </div>
            <div class="panel-body">
                <form method="POST" action="{{ url_for('.register') }}">
                    {{ form.csrf_token }}
                    {% for item in form %}
                    {% if item.errors %}
                    <div class="alert alert-danger">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        {{ item.label }}: {{ item.errors[0] }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="row">
                        <div class="col-xs-12">
                            <label>{{ form.email.label }}</label>
                            {{ form.email(size=20, class="form-control", placeholder=form.email.label.text) }}
                        </div>
                        <div class="col-xs-12">
                            <label>{{ form.password.label }}</label>
                            {{ form.password(size=20, class="form-control", placeholder=form.password.label.text) }}
                        </div>
                        <div class="col-xs-12">
                            <label>{{ form.password_check.label }}</label>
                            {{ form.password_check(size=20, class="form-control", placeholder=form.password_check.label.text) }}
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-success">Start Phantom!</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.pjax.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='js/site.min.js') }}"></script> -->
    <script>{% block script %}{% endblock %}</script>
</body>
</html>